apiVersion: v1
data:
    tunnel-secret.json: ENC[AES256_GCM,data:zgnytgI/zftOovv/8fhumkIDxF3d0H+u44vc9qrQFFajq3HfvgvKB0P2O6RsiqClI6RQBwPPw78Lk4mrrkilkdGfDKuHs2ugqidtlyesi5xlnPkgFuplVE9/U2dQtKojbrR1tAKS3MynZBKnTP3IXCmEMBrBr+q9JbvEwe1IZ7fqwdVFAOGjbwEyqKc9xyJpREh8ukMrDWvZT/Xb/YhCRlYI+Ud5begc1RExZWUg9b3zvVCTjodBHsdi+DMD2xJT92VGudA1bYG2rUN+ZrsqSeQddHXoStejkn/oUyFu9bKCFYch2StZXuajcPY=,iv:FfNxS2M7uLtg3qFNLwnz3+U8XDIQ3kJ08/fTWmqHS9I=,tag:2rDjexEUoCZ/cKWxxZugXA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cloudflare-secret
sops:
    age:
        - recipient: age1xuyqesapjwt8fhejc8cmtf2d2nwkmf2mqj0h4u0nke48lflc84mq9jsfs4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBheVN0TTJEK2oxaXlvb1lk
            MmptYU9BUmVHWUk2RzcvbUZMdUJESTlYTTJ3CkhvYlh0S2cyYnFjMlpBQjZzdTU5
            RGFPekVHM1dnV2dZRGlqU2prZkZIL3cKLS0tIEhOM3pOWTBSNHM2QTE3SlB1ZEps
            TVRaZHdpZ1VEbkFFQlBkM2hRMC9Ja0EKYZqJuKtjFQwo/bRs4favruSfU214HiE0
            NQlB8q3lQSZx7h/CsIp/fK2e4kXIFX+UGjBCOBE4tByZE+52FOeIVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-24T19:12:22Z"
    mac: ENC[AES256_GCM,data:EB5x+9SxmA3279hEAy6UTXxWGFsatbW5bT2kkBOkCAprSZVftgfetNRrCl2UJHopFzDoKE59uX7FxwxAGLs4IV+OPRROxeajPOmARF25qmFiOAIdsSOYpAXYK5KPv+c3rcMF4iLiVYffJNMoTTv7ZxfsNevmYG2h6VUrtMGDyGo=,iv:IYGznnbW7ckm/2NpmP/QwWh7BFB7+i6SaBDQ07tGfdE=,tag:kNTiJEN+nsbvELu7WiZU8w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
