apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      # securityContext:
      #   fsGroup: 33 # www-data group ID
      #   runAsUser: 33 # www-data user ID
      #   runAsGroup: 33 # www-data group ID

      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:latest
          ports:
            - containerPort: 3005
          envFrom:
            - configMapRef:
                name: audiobookshelf-configmap

          # securityContext:
          #   allowPrivilegeEscalation: false

          volumeMounts:
            - mountPath: /etc/audiobookshelf/audiobooks
              name: audiobookshelf-audiobooks
            - mountPath: /etc/audiobookshelf/podcasts
              name: audiobookshelf-podcasts
            - mountPath: /etc/audiobookshelf/config
              name: audiobookshelf-config
            - mountPath: /etc/audiobookshelf/metadata
              name: audiobookshelf-metadata
      volumes:
        - name: audiobookshelf-audiobooks
          persistentVolumeClaim:
            claimName: audiobooks-storage-pvc
        - name: audiobookshelf-podcasts
          persistentVolumeClaim:
            claimName: podcasts-storage-pvc
        - name: audiobookshelf-config
          persistentVolumeClaim:
            claimName: config-storage-pvc
        - name: audiobookshelf-metadata
          persistentVolumeClaim:
            claimName: metadata-storage-pvc
