apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '77.10.0'
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: monitoring
      interval: 12h
  install:
    crds: Create 
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
    ignore:
      # Ignore "validated" annotation which is not inserted during install
      - paths: ['/metadata/annotations/prometheus-operator-validated']
        target:
          kind: PrometheusRule
  values:
    grafana:
      adminPassword: test

      # ingress:
      #   enabled: true
      #   ingressClassName: traefik
      #   hosts:
      #     - grafana.vitalyguzun-homelab.com
      #   tls: []